# Market Data Configuration
data:
  universe:
    type: "static"
    symbols:
      - AAPL
      - MSFT
      - GOOGL
    
  parameters:
    interval: "1d"
    history_start: "2020-01-01"
    add_indicators: true
    cache_data: true
    adjustment: "split+div"

# Strategy Configurations
strategies:
  ma_crossover_aapl:
    type: MovingAverageCrossover
    enabled: true
    symbols: 
      - AAPL
    parameters:
      short_window: 20
      long_window: 50
      
  multi_factor_tech:
    type: MultiFactorStrategy
    enabled: true
    symbols:
      - AAPL
      - MSFT
      - GOOGL
    parameters:
      # Market condition parameters
      market_condition:
        risk_level: "medium"
      
      # Technical indicators configuration
      indicators:
        sma:
          type: "moving_average"
          window: 20
        rsi:
          type: "rsi"
          period: 14
        macd:
          type: "macd"
          fast_period: 12
          slow_period: 26
          signal_period: 9
        bollinger:
          type: "bollinger_bands"
          period: 20
          std_dev: 2
        atr:
          type: "atr"
          period: 14
      
      # Entry conditions
      entry_conditions:
        - type: "rsi_oversold"
          threshold: 30
          weight: 1.0
        - type: "sma_crossover"
          fast_ma: "sma"
          slow_ma: "sma50"
          weight: 0.8
        - type: "macd_crossover"
          weight: 0.7
      
      # Exit conditions
      exit_conditions:
        - type: "rsi_overbought"
          threshold: 70
          weight: 1.0
        - type: "trailing_stop"
          atr_multiplier: 2.0
          weight: 1.0
      
      # Risk filters
      risk_filters:
        volatility:
          type: "atr_filter"
          max_atr_percent: 3.0
        volume:
          type: "volume_filter"
          min_volume: 1000000
        market_cap:
          type: "market_cap_filter"
          min_market_cap: 1000000000
      
      # Position sizing
      position_sizing:
        method: "risk_based"
        risk_per_trade: 0.01
        atr_multiplier: 2.0
      
      # Stop loss and take profit
      stop_loss:
        type: "atr_based"
        multiplier: 2.0
      take_profit:
        type: "atr_based"
        multiplier: 3.0

  # [Other existing strategies remain unchanged...]

# Portfolio Configuration
portfolio:
  initial_capital: 100000
  position_sizing:
    method: "equal"
    max_position_size: 0.20
    max_correlation: 0.70
  
  rebalancing:
    frequency: "monthly"
    threshold: 0.05

# [Rest of the configuration remains unchanged...]
