# Market Data Configuration
data:
  universe:  # Trading universe configuration
    type: "static"  # Options: static, sp500, nasdaq100, etc.
    symbols:
      - AAPL
      - MSFT
      - GOOGL
    # Alternative example for index-based universe:
    # type: "sp500"
    # min_market_cap: 1000000000
    # min_volume: 100000
  
  parameters:
    interval: "1d"    # Data interval (1d, 1h, 5m, etc.)
    history_start: "2020-01-01"
    add_indicators: true
    cache_data: true
    adjustment: "split+div"  # Options: split, div, split+div, none

# Strategy Configurations
strategies:
  ma_crossover_aapl:
    type: MovingAverageCrossover
    enabled: true
    symbols: 
      - AAPL
    parameters:
      short_window: 20
      long_window: 50
      
  rsi_tech_basket:
    type: RSIStrategy
    enabled: true
    symbols:
      - MSFT
      - GOOGL
    parameters:
      period: 14
      overbought: 70
      oversold: 30
      
  bollinger_portfolio:
    type: BollingerBandsStrategy
    enabled: true
    symbols:
      - AAPL
      - MSFT
      - GOOGL
    parameters:
      period: 20
      std_dev: 2
      mean_reversion: true

# Portfolio Configuration
portfolio:
  initial_capital: 100000
  position_sizing:
    method: "equal"  # Options: equal, volatility, capital
    max_position_size: 0.20
    max_correlation: 0.70
  
  rebalancing:
    frequency: "monthly"  # Options: daily, weekly, monthly
    threshold: 0.05  # Minimum deviation to trigger rebalance

# Risk Management
risk_management:
  max_portfolio_risk: 0.02
  stop_loss: 0.02
  trailing_stop: 0.015
  take_profit: 0.04
  max_drawdown_limit: 0.15
  position_sizing_method: "risk_parity"

# Execution Settings
execution:
  commission: 0.001
  slippage: 0.001
  minimum_order_size: 100
  market_impact: 0.0002

# Reporting Configuration
reporting:
  frequency: "daily"
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor