data:
  universe:
    type: "static"
    symbols:
      - AAPL
      - MSFT
  parameters:
    interval: "1d"
    history_start: "2020-01-01"
    add_indicators: true

strategies:
  ma_crossover:
    type: MovingAverageCrossover
    enabled: true
    symbols: 
      - AAPL
    parameters:
      short_window: 20
      long_window: 50