# Market Data Configuration
data:
  universe:
    type: "static"
    symbols:
      - AAPL
      - MSFT
      - GOOGL
    
  parameters:
    interval: "1d"
    history_start: "2020-01-01"
    add_indicators: true
    cache_data: true
    adjustment: "split+div"

# Strategy Configurations
strategies:
  multi_factor_tech:
    enabled: true
    parameters:
      # Market condition parameters
      market_condition:
        risk_level: "medium"

      
      # Entry conditions
      entry_conditions:
        - type: "rsi_oversold"
          threshold: 30
          weight: 1.0
        - type: "sma_crossover"
          fast_ma: "sma20"
          slow_ma: "sma50"
          weight: 0.8
      
      # Exit conditions
      exit_conditions:
        - type: "rsi_overbought"
          threshold: 70
          weight: 1.0
        - type: "trailing_stop"
          atr_multiplier: 2.0
          weight: 1.0
      
      # Risk filters
      risk_filters:
        volatility:
          type: "atr_filter"
          max_atr_percent: 3.0
        volume:
          type: "volume_filter"
          min_volume: 1000000

# Portfolio Configuration
portfolio:
  initial_capital: 100000
  position_sizing:
    method: "equal"
    max_position_size: 0.20
    max_correlation: 0.70
  
  rebalancing:
    frequency: "monthly"
    threshold: 0.05

# Risk Management
risk_management:
  max_portfolio_risk: 0.02
  stop_loss: 0.02
  trailing_stop: 0.015
  take_profit: 0.04
  max_drawdown_limit: 0.15