# Universe
symbols: ["PLTR", "SOFI", "IONQ", "VRT", "QQQ", "SPY", "AAPL", "TSLA", "AMZN", "GOOGL"]
timeframe: "1m"
start_date: "2024-01-01"
end_date: "2024-12-31"

# Stage 2 (Markup) entry conditions
entry_conditions:
  - indicator: "close"
    comparison: "above"
    value: "sma_20"
  - indicator: "ema_5"
    comparison: "crosses_above"
    value: "sma_20"

# Stage 4 (Markdown) exit conditions
exit_conditions:
  - indicator: "close"
    comparison: "below"
    value: "ema_20"
  - indicator: "ema_5"
    comparison: "crosses_below"
    value: "ema_20"
  # Price breaking below bands
  - indicator: "close"
    comparison: "below"
    value: "lowerband"

# Risk management parameters
risk_management:
  position_sizing_method: "risk_based"
  risk_per_trade: 0.1
  stop_loss: 0.02
  take_profit: 0.06
  max_position_size: 1000.0
  atr_multiplier: 2.0

# Required indicators for all stages
indicators:
  - name: "EMA"
    params:
      period: 5
  - name: "EMA"
    params:
      period: 20
  - name: "SMA"
    params:
      period: 20
  - name: "SMA"
    params:
      period: 50
  - name: "RSI"
    params:
      period: 14
  - name: "BBANDS"
    params:
      period: 20
      std_dev: 2
  - name: "ATR"
    params:
      period: 14
