symbol: "SPY"
timeframe: "1h"
mode: "backtest"

risk_management:
  position_sizing_method: "atr_based"  # Options: fixed, risk_based, atr_based
  risk_per_trade: 0.10  # 2% risk per trade
  max_position_size: 1000
  stop_loss: 0.05  # 5% stop loss
  take_profit: 0.10  # 10% take profit
  max_drawdown: 0.15  # 15% max drawdown
  atr_multiplier: 2.0

indicators:
  - name: "RSI"
    params:
      timeperiod: 14
  
  - name: "BBANDS"
    params:
      timeperiod: 20
      nbdevup: 1.5
      nbdevdn: 1.5
      matype: 0
  
  - name: "ATR"
    params:
      timeperiod: 14

# FOR BBANDS: value==, ["lowerband", "middleband", "upperband"]

entry_conditions:
  - indicator: "RSI"
    comparison: "below"
    value: 30  # compares macd line crossing above signal line
    
  - indicator: "BBANDS"
    comparison: "crosses_below"
    value: "lowerband"   
exit_conditions:
  - indicator: "RSI"
    comparison: "above"
    value: 75
    
  - indicator: "ATR"
    comparison: "above"
    value: 25