symbols: ["AAPL", "MSFT", "GOOG"]
timeframe: "1d"
start_date: "2024-01-01"
end_date: "2024-12-31"

# Entry conditions
entry_conditions:
  - indicator: "ema_5"
    comparison: "crosses_above"
    value: "sma_20"
  - indicator: "rsi"
    comparison: "below"
    value: "45"
  - indicator: "open"
    comparison: "above"
    value: "high"

# Exit conditions
exit_conditions:
  - indicator: "rsi"
    comparison: "crosses_above"
    value: "75"

# Risk management parameters
risk_management:
  position_sizing_method: "risk_based"
  risk_per_trade: 15
  stop_loss: 0.15
  take_profit: 0.2
  max_position_size: 960
  atr_multiplier: 0

# Required indicators
indicators:
  - name: "SMA"
    params:
      period: 20
  - name: "EMA"
    params:
      period: 5
  - name: "RSI"
    params:
      period: 14
