symbol: "ETHUSD"
timeframe: "1h"
mode: "backtest"

risk_management:
  position_sizing_method: "atr_based"  # Options: fixed, risk_based, atr_based
  risk_per_trade: 0.02  # 2% risk per trade
  max_position_size: 1.0
  stop_loss: 0.02  # 2% stop loss
  take_profit: 0.04  # 4% take profit
  max_drawdown: 0.15  # 15% max drawdown
  atr_multiplier: 2.0

entry_conditions:
  - indicator: "MACD"
    params:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    comparison: "crosses_above"
    threshold: 0

  - indicator: "Bollinger"
    params:
      window: 20
      std_dev: 2
    comparison: "crosses_below"
    threshold: "lower"  # Using the lower band

exit_conditions:
  - indicator: "ATR"
    params:
      window: 14
    comparison: "above"
    threshold: 15

  - indicator: "RSI"
    params:
      window: 14
    comparison: "crosses_above"
    threshold: 70